version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install pytest requests
  build:
    commands:
      - pytest tests/
artifacts:
  files:
    - '**/*'
  discard-paths: yes
